model:
    name: qwen_image
    pretrained_model_name_or_path: /path/to/Qwen/Qwen-Image
    fake:
        name: qwen_image
        pretrained_model_name_or_path: /path/to/Qwen/Qwen-Image
    teacher:
        name: qwen_image
        pretrained_model_name_or_path: /path/to/Qwen/Qwen-Image
    max_sequence_length: 1024
    running_dtype: bf16

data:
    train:
        name: image_dataset
        num_workers: 8
        prompt_dropout_rate: 0.0
        target_area: 1048576 # 1024 * 1024
        shuffle: true
        data_path:
            - /path/to/LightX2V_train_data_examples/dataset_v1/train.jsonl
    val:
        name: image_dataset
        num_workers: 8
        shuffle: false
        data_path:
            - /path/to/LightX2V_train_data_examples/dataset_v1/val.jsonl

scheduler:
    num_train_timesteps: 1000
    time_shift_settings:
        do_time_shift: true
        shift_type: linear
        # shift function: "linear" => mu/(mu+(1/t-1)^p), "exponential" => exp(mu)/(exp(mu)+(1/t-1)^p)
        time_shift_power: 1.0
        dynamic_shift: false
        time_shift_mu: 3.0

training:
    method: dmd
    train_type: lora
    max_train_iters: 1000
    gradient_accumulation_iters: 1
    gradient_checkpointing: true
    max_grad_norm: 1.0
    lr_scheduler: constant
    lr_warmup_iters: 10
    save_every_iters: 100
    save_total_limit: 10
    dmd:
        num_inference_steps: 4
        fake_update_ratio: 2
        image_sizes:
            - [1024, 1024]
            - [768, 1344]
            - [1344, 768]
        renoise_sigma_min: 0.02
        renoise_sigma_max: 1.0
        renoise_discrete_samples: 1000
        renoise_shift: 5.0
    lora:
        rank: 32
        alpha: 32
        target_modules:
            - to_k
            - to_q
            - to_v
            - to_out.0
            # - add_q_proj
            # - add_k_proj
            # - add_v_proj
            # - to_add_out
            # - img_mlp.net.0.proj
            # - img_mlp.net.2
            # - txt_mlp.net.0.proj
            # - txt_mlp.net.2
    student:
        optimizer:
            learning_rate: 0.0001
            adam_beta1: 0.9
            adam_beta2: 0.999
            weight_decay: 0.001
            adam_epsilon: 0.00000001
    fake:
        optimizer:
            learning_rate: 0.00002
            adam_beta1: 0.9
            adam_beta2: 0.999
            weight_decay: 0.001
            adam_epsilon: 0.00000001
    teacher:
        guidance_scale: 4.0
        negative_prompt: " "
        cfg_norm: layer_norm
    output_dir: ./output_train/qwen_image_dmd_lora

inference:
    method: image_infer
    default_width: 1024
    default_height: 1024
    num_inference_steps: 4
    cfg_guidance_scale: 4.0
    negative_prompt: " "
    enable_cfg: false
    output_dir: ./output_infer/qwen_image_dmd_lora
    infer_every_iters: ${training.save_every_iters}

logging:
    rank_zero_only: true
    train_log_every_iters: 10
    infer_log_every_steps: 10

resume:
    auto_resume: true
