FROM lightx2v/lightx2v:26062002-cu130-5090-ros2-jazzy AS base
# ubuntu 24.04 python 3.12 torch 2.11 cuda 13.0

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends aria2 ca-certificates && aria2c -x 16 -s 16 -k 1M -c --max-tries=0 --retry-wait=10 -o isaac-sim-standalone-6.0.1-linux-x86_64.zip https://downloads.isaacsim.nvidia.com/isaac-sim-standalone-6.0.1-linux-x86_64.zip
RUN mkdir /app/isaacsim && unzip isaac-sim-standalone-6.0.1-linux-x86_64.zip -d /app/isaacsim

RUN git clone https://github.com/ModelTC/IsaacLab.git --branch v3.0.0-beta2.patch1.no-torch
RUN cd IsaacLab && PATH=/usr/bin:$PATH ./isaaclab.sh --install
