FROM lightx2v/lightx2v:26062001-cu130-5090 AS base
# ubuntu 24.04 python 3.12 torch 2.11 cuda 13.0

WORKDIR /app

RUN pip uninstall -y sageattention && rm -rf /app/SageAttention

RUN git clone https://github.com/ModelTC/SageAttention.git --depth 1

RUN cd SageAttention && \
    CUDA_ARCHITECTURES="8.0,8.6,8.9,9.0,12.0" \
    EXT_PARALLEL=4 \
    NVCC_APPEND_FLAGS="--threads 8" \
    MAX_JOBS=32 \
    pip install --no-cache-dir --no-build-isolation -v -e .

WORKDIR /workspace
