FROM lightx2v/lightx2v:26062001-cu130 AS base
# ubuntu 24.04 python 3.12 torch 2.11 cuda 13.0

RUN apt update && apt install locales
RUN locale-gen en_US en_US.UTF-8
RUN update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV LANG=en_US.UTF-8


RUN apt install software-properties-common -y
RUN add-apt-repository universe -y


RUN apt update && apt install curl -y

RUN export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F'"' '{print $4}') \
    && curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo ${UBUNTU_CODENAME:-${VERSION_CODENAME}})_all.deb" \
    && dpkg -i /tmp/ros2-apt-source.deb


RUN apt update && apt install -y ros-dev-tools


RUN mkdir -p ~/ros2_lyrical/src
WORKDIR /root/ros2_lyrical
RUN vcs import --input https://raw.githubusercontent.com/ros2/ros2/lyrical/ros2.repos src


RUN rosdep init
RUN rosdep update
RUN rosdep install --from-paths src --ignore-src -y --skip-keys "fastcdr rti-connext-dds-7.7.0 urdfdom_headers"


RUN colcon mixin add default https://github.com/colcon/colcon-mixin-repository/raw/master/index.yaml
RUN colcon mixin update default


RUN pip uninstall setuptools-scm
RUN pip install catkin_pkg empy pyqt5-sip PyQt5 sip==6.15.3 setuptools==79.0.1


WORKDIR /root/ros2_lyrical
RUN colcon build --symlink-install --mixin release

WORKDIR /root


# Test ROS2

# Talker
# . ~/ros2_lyrical/install/local_setup.bash
# ros2 run demo_nodes_cpp talker

# Listener
# . ~/ros2_lyrical/install/local_setup.bash
# ros2 run demo_nodes_py listener
